name: first-action
on: push
jobs:
  testJob:
    runs-on: ubuntu-latest
    steps:
        - name: Get code #steps
          uses: actions/checkout@v3
        - name: install nodeJs
          uses: actions/setup-node@v3
          with: 
            node-version: 18
        - name: install dependencies
          run: npm ci